### ISSUE TITLE
Tests for Lexer and Parser classes

### ISSUE THREAD

**Issue by comp-phys-marc** [comp-phys-marc/qasm-ts#1]
This package previously had a test suite that was based on the now-outdated conformance test suite specified by OpenQASM [here](https://github.com/Qiskit/openqasm/tree/89619c3acdedaa461ed545c558055215ac30b06a/examples). I would love help to write a test suite like the one in qmasm-ts [here](https://github.com/comp-phys-marc/qmasm-ts/tree/master/spec) that covers the features of the language, to start. It would be great to then expand further to individually unittest the methods of the lexer and parser classes.

**Comment by comp-phys-marc** [comment]
Inspiration for updated smoke tests may take inspiration from the OpenQASM 2.0 tests, some of which are preserved in the `feature/v2.0specs` [branch](https://github.com/comp-phys-marc/qasm-ts/tree/feature/v2.0specs/spec).

**Comment by seankim658** [comment]
Was running some OpenQASM 2.0 from the old `features/v2.0specs` branch to make sure no backwards compatibility was broken while adding new features and found [this](https://github.com/comp-phys-marc/qasm-ts/blob/482b21a9707585afaba1172492c505edd9dd3535/spec/tokens/ibmqx2/Deutsch_Algorithm.ts#L14) bug. The lexer was lexing `Creg` declarations to `QReg` tokens [here](https://github.com/comp-phys-marc/qasm-ts/blob/a9541fe9a2b0b9112ef838d00c91fd6770cdc10c/src/lexer.ts#L265). This has been fixed in the `openqasm-3.0` branch but just making a note of it as the test snapshots will have to be updated when they are eventually ported over.
